### ISSUE TITLE
tts插件启动失败，疑似是 i18n 的问题

### ISSUE THREAD

**Issue by frostime** [zuoez02/siyuan-plugin-tts#3]
https://ld246.com/article/1689480216878

![c7d9cc23c752e390dbea44a5df12f1f7](https://github.com/zuoez02/siyuan-plugin-tts/assets/27268127/53fbedea-0df0-4906-8d89-129bbf11debc)

这里的 title 是 onload 里的 `this.status = this.i18n.title;` 。

我看了一下插件的文件夹，没有i18n文件夹， zh_CN.json 等文件都平铺放在了根目录下。可能是是你打包的时候把 i18n 的目录结构破坏了。

![image](https://github.com/zuoez02/siyuan-plugin-tts/assets/27268127/675f1d75-4387-4562-8348-483760fe8516)

**Comment by zuoez02** [comment]
嗯嗯，自动化的问题

**Comment by zuoez02** [comment]
已修复，确实是CI的问题
